AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  PitagoraSwitch:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: pitagoraOn
      Policies:
        Statement:
          - Effect: Allow
            Action: "ssm:GetParameter"
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/pitagora-switch-*'
